[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "kAOV" 
version = "1.4.1"
description = "Kernel Analysis of Variance"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE.txt"}
keywords = ["kernel methods", "analysis of variance"]
authors = [
  {name = "Polina Arsenteva", email = "polina.arsenteva@ens-lyon.fr" },
  {name = "Anthony Ozier-Lafontaine", email = "antho.ozier.laf@gmail.com" },
  {name = "Ghislain Durif", email = "ghislain.durif@ens-lyon.fr"}
]
maintainers = [
  {name = "Polina Arsenteva", email = "polina.arsenteva@ens-lyon.fr" }
]
dependencies = [
  "matplotlib",
  "numpy < 2",
  "pandas",
  "scipy",
  "patsy",
  "torch >= 2.2.0",
  "statsmodels >= 0.14.0",
  "tqdm",
]

